import type { ActiveCamera, MatchMetadata, PlayerLive, PlayerRegistry } from '@/types/livestats';

export const MOCK_MATCH: MatchMetadata = {
  id: 1,
  match_guid: 'mock-guid',
  timer: '3:42',
  time_seconds: 222,
  blue_score: 2,
  orange_score: 1,
  is_overtime: false,
  updated_at: new Date().toISOString(),
  is_active: true,
};

export const MOCK_PLAYERS: PlayerLive[] = [
  {
    player_name: 'Phantom',
    team_num: 0,
    boost: 78,
    speed: 1700,
    goals: 2,
    assists: 1,
    saves: 3,
    shots: 5,
    demos: 1,
    is_demolished: false,
    is_supersonic: false,
    mmr: 1850,
    updated_at: new Date().toISOString(),
  },
  {
    player_name: 'Vortex',
    team_num: 0,
    boost: 100,
    speed: 2100,
    goals: 1,
    assists: 2,
    saves: 1,
    shots: 4,
    demos: 0,
    is_demolished: false,
    is_supersonic: true,
    mmr: 1920,
    updated_at: new Date().toISOString(),
  },
  {
    player_name: 'Reaper',
    team_num: 0,
    boost: 33,
    speed: 1100,
    goals: 0,
    assists: 1,
    saves: 2,
    shots: 2,
    demos: 2,
    is_demolished: false,
    is_supersonic: false,
    mmr: 1780,
    updated_at: new Date().toISOString(),
  },
  {
    player_name: 'Blaze',
    team_num: 1,
    boost: 56,
    speed: 1500,
    goals: 1,
    assists: 0,
    saves: 2,
    shots: 3,
    demos: 1,
    is_demolished: false,
    is_supersonic: false,
    mmr: 1810,
    updated_at: new Date().toISOString(),
  },
  {
    player_name: 'Inferno',
    team_num: 1,
    boost: 12,
    speed: 800,
    goals: 0,
    assists: 1,
    saves: 0,
    shots: 1,
    demos: 0,
    is_demolished: true,
    is_supersonic: false,
    mmr: 1690,
    updated_at: new Date().toISOString(),
  },
  {
    player_name: 'Solar',
    team_num: 1,
    boost: 88,
    speed: 1900,
    goals: 0,
    assists: 0,
    saves: 1,
    shots: 2,
    demos: 0,
    is_demolished: false,
    is_supersonic: false,
    mmr: 1750,
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_CAMERA: ActiveCamera = {
  id: 1,
  target_name: 'Vortex',
  updated_at: new Date().toISOString(),
};

export const MOCK_SERIES = {
  type: 'bo5' as const,
  blueScore: 2,
  orangeScore: 1,
  blueName: 'Team Blue',
  orangeName: 'Team Orange',
};

export const MOCK_REGISTRY: PlayerRegistry[] = [
  {
    player_name: 'Phantom',
    display_name: 'Phantom',
    photo_url: null,
    country_code: 'PL',
    rank_name: 'Diamond II',
    mmr: 1850,
    team_color: null,
    notes: null,
  },
  {
    player_name: 'Vortex',
    display_name: 'Vortex',
    photo_url: null,
    country_code: 'PL',
    rank_name: 'Champion I',
    mmr: 1920,
    team_color: null,
    notes: null,
  },
  {
    player_name: 'Reaper',
    display_name: 'Reaper',
    photo_url: null,
    country_code: 'DE',
    rank_name: 'Diamond III',
    mmr: 1780,
    team_color: null,
    notes: null,
  },
  {
    player_name: 'Blaze',
    display_name: 'Blaze',
    photo_url: null,
    country_code: 'FR',
    rank_name: 'Diamond III',
    mmr: 1810,
    team_color: null,
    notes: null,
  },
  {
    player_name: 'Inferno',
    display_name: 'Inferno',
    photo_url: null,
    country_code: 'NL',
    rank_name: 'Diamond I',
    mmr: 1690,
    team_color: null,
    notes: null,
  },
  {
    player_name: 'Solar',
    display_name: 'Solar',
    photo_url: null,
    country_code: 'ES',
    rank_name: 'Diamond II',
    mmr: 1750,
    team_color: null,
    notes: null,
  },
];

export function buildMockRegistryMap(): Map<string, PlayerRegistry> {
  const m = new Map<string, PlayerRegistry>();
  for (const r of MOCK_REGISTRY) m.set(r.player_name, r);
  return m;
}
