import type { OverlayConfig, ElementShape } from '@/types/broadcast';

export interface OverlayTemplate {
  id: string;
  name: string;
  description: string;
  config: OverlayConfig;
}

// RLCS Classic - Kompaktowy styl turniejowy
const rlcsClassicConfig: OverlayConfig = {
  scoreboard: {
    visible: true,
    position: { x: 50, y: 2 },
    width: 600,
    height: 70,
    backgroundColor: 'rgba(10, 12, 18, 0.95)',
    borderRadius: 8,
    borderWidth: 0,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    gap: 12,
    layout: 'horizontal',
    edgeStyle: 'rounded',
    shape: 'rounded',
  },
  scoreDisplay: {
    visible: true,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 6,
    borderWidth: 0,
    borderColor: 'transparent',
    padding: 10,
    fontFamily: 'Inter',
    fontSize: 32,
    textColor: '#ffffff',
    opacity: 1,
    gap: 10,
    separatorColor: 'rgba(255, 255, 255, 0.2)',
    separatorWidth: 1,
  },
  timerDisplay: {
    visible: true,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 4,
    borderWidth: 0,
    borderColor: 'transparent',
    padding: 8,
    fontFamily: 'JetBrains Mono',
    fontSize: 18,
    textColor: '#ffffff',
    opacity: 1,
    showOvertimeLabel: true,
    overtimeLabelColor: '#F59E0B',
  },
  seriesDisplay: {
    visible: true,
    backgroundColor: 'transparent',
    borderRadius: 4,
    borderWidth: 0,
    borderColor: 'transparent',
    padding: 4,
    fontFamily: 'Inter',
    fontSize: 11,
    textColor: '#ffffff',
    opacity: 1,
    showSeriesType: true,
    dotSize: 6,
    dotSpacing: 3,
    activeDotColor: '#22C55E',
    inactiveDotColor: 'rgba(255, 255, 255, 0.2)',
  },
  teamAName: {
    visible: true,
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    borderColor: 'transparent',
    padding: 0,
    fontFamily: 'Inter',
    fontSize: 16,
    textColor: '#ffffff',
    opacity: 1,
    maxWidth: 130,
    showLogo: true,
    logoSize: 36,
    logoPosition: 'left',
  },
  teamBName: {
    visible: true,
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    borderColor: 'transparent',
    padding: 0,
    fontFamily: 'Inter',
    fontSize: 16,
    textColor: '#ffffff',
    opacity: 1,
    maxWidth: 130,
    showLogo: true,
    logoSize: 36,
    logoPosition: 'right',
  },
  boostBars: {
    visible: true,
    position: 'bottom-corners',
    verticalPosition: 66,
    horizontalPadding: 20,
    width: 180,
    height: 140,
    barHeight: 6,
    boostBarWidth: 80,
    backgroundColor: 'rgba(10, 12, 18, 0.9)',
    borderRadius: 4,
    edgeStyle: 'rounded',
    shape: 'rounded',
    showPlayerNames: true,
    showBoostValue: true,
    fontFamily: 'Inter',
    fontSize: 12,
    teamAColor: '#3B82F6',
    teamBColor: '#F97316',
    animationSpeed: 120,
  },
  boostCircle: {
    visible: true,
    position: { x: 95, y: 85 },
    size: 90,
    strokeWidth: 6,
    backgroundColor: 'rgba(10, 12, 18, 0.85)',
    fillColor: '#3B82F6',
    showValue: true,
    fontFamily: 'JetBrains Mono',
    fontSize: 24,
    textColor: '#ffffff',
    animationSpeed: 100,
  },
  playerStats: {
    visible: true,
    position: { x: 5, y: 90 },
    width: 280,
    height: 50,
    backgroundColor: 'rgba(10, 12, 18, 0.85)',
    borderRadius: 4,
    showGoals: true,
    showShots: true,
    showAssists: true,
    showSaves: true,
    showScore: true,
    fontFamily: 'Inter',
    fontSize: 11,
    textColor: '#ffffff',
  },
  general: {
    backgroundColor: 'transparent',
    animationsEnabled: true,
    transitionDuration: 120,
  },
};

// Tournament Pro - Szeroki pasek z kolorowymi tłami
const tournamentProConfig: OverlayConfig = {
  ...rlcsClassicConfig,
  scoreboard: {
    ...rlcsClassicConfig.scoreboard,
    width: 750,
    height: 80,
    backgroundColor: 'rgba(15, 17, 23, 0.98)',
    borderRadius: 0,
    edgeStyle: 'sharp',
    shape: 'sharp',
  },
  scoreDisplay: {
    ...rlcsClassicConfig.scoreDisplay,
    fontSize: 38,
    borderRadius: 0,
  },
  timerDisplay: {
    ...rlcsClassicConfig.timerDisplay,
    fontSize: 22,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 0,
  },
  teamAName: {
    ...rlcsClassicConfig.teamAName,
    fontSize: 18,
    maxWidth: 160,
    logoSize: 42,
  },
  teamBName: {
    ...rlcsClassicConfig.teamBName,
    fontSize: 18,
    maxWidth: 160,
    logoSize: 42,
  },
  boostBars: {
    ...rlcsClassicConfig.boostBars,
    width: 220,
    barHeight: 8,
    boostBarWidth: 100,
    fontSize: 14,
    borderRadius: 0,
    edgeStyle: 'sharp',
    shape: 'sharp',
    backgroundColor: 'rgba(15, 17, 23, 0.95)',
  },
};

// Minimalist Dark - Ciemny, elegancki design
const minimalistDarkConfig: OverlayConfig = {
  ...rlcsClassicConfig,
  scoreboard: {
    ...rlcsClassicConfig.scoreboard,
    width: 500,
    height: 60,
    backgroundColor: 'rgba(5, 7, 12, 0.92)',
    borderRadius: 16,
    edgeStyle: 'rounded',
    shape: 'pill',
  },
  scoreDisplay: {
    ...rlcsClassicConfig.scoreDisplay,
    fontSize: 28,
    borderRadius: 12,
  },
  timerDisplay: {
    ...rlcsClassicConfig.timerDisplay,
    fontSize: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 8,
  },
  seriesDisplay: {
    ...rlcsClassicConfig.seriesDisplay,
    dotSize: 5,
    dotSpacing: 2,
  },
  teamAName: {
    ...rlcsClassicConfig.teamAName,
    fontSize: 14,
    maxWidth: 100,
    logoSize: 30,
  },
  teamBName: {
    ...rlcsClassicConfig.teamBName,
    fontSize: 14,
    maxWidth: 100,
    logoSize: 30,
  },
  boostBars: {
    ...rlcsClassicConfig.boostBars,
    width: 160,
    barHeight: 5,
    boostBarWidth: 70,
    fontSize: 11,
    borderRadius: 12,
    edgeStyle: 'rounded',
    shape: 'pill',
    backgroundColor: 'rgba(5, 7, 12, 0.88)',
  },
  boostCircle: {
    ...rlcsClassicConfig.boostCircle,
    size: 80,
    strokeWidth: 5,
    fontSize: 20,
    backgroundColor: 'rgba(5, 7, 12, 0.85)',
  },
};

// Modern Esport - Skośne krawędzie, gradientowe tła
const modernEsportConfig: OverlayConfig = {
  ...rlcsClassicConfig,
  scoreboard: {
    ...rlcsClassicConfig.scoreboard,
    width: 680,
    height: 75,
    backgroundColor: 'rgba(12, 14, 20, 0.96)',
    borderRadius: 0,
    edgeStyle: 'skewed',
    shape: 'skewed',
  },
  scoreDisplay: {
    ...rlcsClassicConfig.scoreDisplay,
    fontSize: 34,
    borderRadius: 0,
  },
  timerDisplay: {
    ...rlcsClassicConfig.timerDisplay,
    fontSize: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 0,
  },
  teamAName: {
    ...rlcsClassicConfig.teamAName,
    fontSize: 17,
    maxWidth: 140,
    logoSize: 38,
  },
  teamBName: {
    ...rlcsClassicConfig.teamBName,
    fontSize: 17,
    maxWidth: 140,
    logoSize: 38,
  },
  boostBars: {
    ...rlcsClassicConfig.boostBars,
    width: 200,
    barHeight: 7,
    boostBarWidth: 90,
    fontSize: 13,
    borderRadius: 0,
    edgeStyle: 'skewed',
    shape: 'skewed',
    backgroundColor: 'rgba(12, 14, 20, 0.92)',
  },
  boostCircle: {
    ...rlcsClassicConfig.boostCircle,
    size: 95,
    strokeWidth: 7,
    fontSize: 26,
  },
};

export const OVERLAY_TEMPLATES: OverlayTemplate[] = [
  {
    id: 'rlcs_classic',
    name: 'RLCS Classic',
    description: 'Klasyczny styl turniejów Rocket League',
    config: rlcsClassicConfig,
  },
  {
    id: 'tournament_pro',
    name: 'Tournament Pro',
    description: 'Szeroki pasek z kolorowymi tłami drużyn',
    config: tournamentProConfig,
  },
  {
    id: 'minimalist_dark',
    name: 'Minimalist Dark',
    description: 'Ciemny, elegancki design z zaokrągleniami',
    config: minimalistDarkConfig,
  },
  {
    id: 'modern_esport',
    name: 'Modern Esport',
    description: 'Nowoczesny styl ze skośnymi krawędziami',
    config: modernEsportConfig,
  },
];

export function getTemplateById(id: string): OverlayTemplate | undefined {
  return OVERLAY_TEMPLATES.find(t => t.id === id);
}
